2021-06-02 22:54:04,852 - c:\users\aarc8\documents\github\mdoairb\framework\utilities\output     - INFO - ==== Start writing klm results ====
2021-06-02 22:54:04,931 - c:\users\aarc8\documents\github\mdoairb\framework\utilities\output     - INFO - ==== End writing klm results ====
INFO - Aircraft passed sizing and checks status: 0
2021-06-02 22:54:04,793 - c:\Users\aarc8\Documents\github\MDOAirB\framework\Optimization\objective_function_real     - INFO - ---- Start DOC matrix calculation ----
2021-06-02 22:54:04,798 - c:\Users\aarc8\Documents\github\MDOAirB\framework\Optimization\objective_function_real     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< DOC matrix generation
Traceback (most recent call last):
  File "c:\Users\aarc8\Documents\github\MDOAirB\framework\Optimization\objective_function_real.py", line 180, in objective_function_0
    fuel_mass[departures[i]][arrivals[k]], total_mission_flight_time[departures[i]][arrivals[k]], DOC,mach[departures[i]][arrivals[k]],passenger_capacity[departures[i]][arrivals[k]], SAR[departures[i]][arrivals[k]] = mission(departures[i],arrivals[k],heading,vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Performance\Mission\mission_real.py", line 72, in mission
    mission_range = actual_mission_range(departure,arrival)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Attributes\Mission\mission_parameters.py", line 13, in actual_mission_range
    listOfFiles = os.listdir('Database/Routes/'+ departure+'_'+arrival+'/.')
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'Database/Routes/CD0_CD1/.'
2021-06-02 22:54:04,809 - c:\Users\aarc8\Documents\github\MDOAirB\framework\Optimization\objective_function_real     - INFO - Aircraft DOC matrix: {'CD0': {'CD0': 0}}
2021-06-02 22:54:04,811 - c:\Users\aarc8\Documents\github\MDOAirB\framework\Optimization\objective_function_real     - INFO - ---- Start Network Optimization ----
2021-06-02 22:54:04,812 - c:\Users\aarc8\Documents\github\MDOAirB\framework\Optimization\objective_function_real     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< network_optimization
Traceback (most recent call last):
  File "c:\Users\aarc8\Documents\github\MDOAirB\framework\Optimization\objective_function_real.py", line 215, in objective_function_0
    arrivals, departures, distances, demand,active_airports ,DOC_ik, pax_capacity, vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Network\network_optimization.py", line 59, in network_optimization
    DOC[(i, k)] = np.round(doc0[i][k])
KeyError: 'CD1'
2021-06-02 22:54:04,814 - c:\Users\aarc8\Documents\github\MDOAirB\framework\Optimization\objective_function_real     - INFO - Network profit [$USD]: 0
2021-06-02 22:54:04,842 - c:\Users\aarc8\Documents\github\MDOAirB\framework\Optimization\objective_function_real     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< writting dataframes
Traceback (most recent call last):
  File "c:\Users\aarc8\Documents\github\MDOAirB\framework\Optimization\objective_function_real.py", line 260, in objective_function_0
    kpi_df3['mach'] = mach_df['mach'].values
  File "C:\Users\aarc8\.conda\envs\MDOAirB\lib\site-packages\pandas\core\frame.py", line 3044, in __setitem__
    self._set_item(key, value)
  File "C:\Users\aarc8\.conda\envs\MDOAirB\lib\site-packages\pandas\core\frame.py", line 3120, in _set_item
    value = self._sanitize_column(key, value)
  File "C:\Users\aarc8\.conda\envs\MDOAirB\lib\site-packages\pandas\core\frame.py", line 3768, in _sanitize_column
    value = sanitize_index(value, self.index)
  File "C:\Users\aarc8\.conda\envs\MDOAirB\lib\site-packages\pandas\core\internals\construction.py", line 748, in sanitize_index
    "Length of values "
ValueError: Length of values (1) does not match length of index (100)
2021-06-02 22:54:04,849 - c:\Users\aarc8\Documents\github\MDOAirB\framework\Optimization\objective_function_real     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_optimal_results
Traceback (most recent call last):
  File "c:\Users\aarc8\Documents\github\MDOAirB\framework\Optimization\objective_function_real.py", line 295, in objective_function_0
    write_optimal_results(profit, DOC_ik, vehicle, kpi_df2)
UnboundLocalError: local variable 'kpi_df2' referenced before assignment
2021-06-02 22:54:04,931 - c:\Users\aarc8\Documents\github\MDOAirB\framework\Optimization\objective_function_real     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_newtork_results
Traceback (most recent call last):
  File "c:\Users\aarc8\Documents\github\MDOAirB\framework\Optimization\objective_function_real.py", line 305, in objective_function_0
    write_newtork_results(profit,kpi_df1,kpi_df2)
UnboundLocalError: local variable 'kpi_df1' referenced before assignment
2021-06-02 22:54:04,934 - c:\Users\aarc8\Documents\github\MDOAirB\framework\Optimization\objective_function_real     - INFO - Network profit excecution time: 0:03:54.342331
2021-06-02 22:54:04,938 - c:\Users\aarc8\Documents\github\MDOAirB\framework\Optimization\objective_function_real     - INFO - ==== End network profit module ====
